blank_issues_enabled: false
contact_links:
  - name: Support & Questions
    url: https://github.com/alexdelprete/ha-abb-fimer-pvi-vsn-rest/discussions
    about: Get help with setup and configuration
  - name: Feature Ideas
    url: https://github.com/alexdelprete/ha-abb-fimer-pvi-vsn-rest/discussions/categories/ideas
    about: Share and discuss feature ideas
